import { MigrationInterface, QueryRunner } from "typeorm";

export class AddOperatorIdRest1783159354624 implements MigrationInterface {
    name = 'AddOperatorIdRest1783159354624'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_e623318f79b0e8cdd4d5fa99ec\` ON \`keno_configs\``);
        await queryRunner.query(`DROP INDEX \`UQ_bingo_active_game\` ON \`bingo_rooms\``);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`rng_audit_logs\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`wager_limits\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_configs\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_cards\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`refresh_sessions\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`admin_audit_logs\` ADD \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_ecc52116ea1cd32c3379352416\` ON \`auth_identities\``);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`providerUsername\` \`providerUsername\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`normalizedEmail\` \`normalizedEmail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`passwordHash\` \`passwordHash\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` DROP COLUMN \`profileSnapshot\``);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` ADD \`profileSnapshot\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`wallets\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` DROP FOREIGN KEY \`FK_7739ad242a592b3e80d86a4c42b\``);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` CHANGE \`label\` \`label\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_57d6dcdfa66baa83402ca3abac\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_217a7b342e187cdd5c49c06ea8\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLoginAt\` \`lastLoginAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`responsibleGamingFlags\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`responsibleGamingFlags\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`productMetadata\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`productMetadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workStartHour\` \`workStartHour\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workStartMinute\` \`workStartMinute\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workEndHour\` \`workEndHour\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workEndMinute\` \`workEndMinute\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`agentPermissions\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`agentPermissions\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` DROP FOREIGN KEY \`FK_c9e099b1be330ca21906b5d4b36\``);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` DROP FOREIGN KEY \`FK_a12d7d24d3d1071edcaffbe7120\``);
        await queryRunner.query(`DROP INDEX \`IDX_d15ac889f39c4793b9eb0554c4\` ON \`withdrawals\``);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`agentId\` \`agentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`claimedAt\` \`claimedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`netAmountMinor\` \`netAmountMinor\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`telebirrReference\` \`telebirrReference\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`adminNotes\` \`adminNotes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`processedBy\` \`processedBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`processedAt\` \`processedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`processorId\` \`processorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`rng_audit_logs\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`rng_audit_logs\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` DROP FOREIGN KEY \`FK_3601e114fb791d969f6694c8db5\``);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`agentId\` \`agentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`payerName\` \`payerName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`payerPhone\` \`payerPhone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`creditedPartyName\` \`creditedPartyName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`creditedPartyAccount\` \`creditedPartyAccount\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`transactionStatus\` \`transactionStatus\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` DROP COLUMN \`verification\``);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` ADD \`verification\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` DROP COLUMN \`walletCredit\``);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` ADD \`walletCredit\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`operator_configs\` CHANGE \`telegramBotToken\` \`telegramBotToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`operator_configs\` CHANGE \`telegramBotUsername\` \`telegramBotUsername\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`operators\` CHANGE \`customDomain\` \`customDomain\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`operators\` DROP COLUMN \`branding\``);
        await queryRunner.query(`ALTER TABLE \`operators\` ADD \`branding\` json NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_38e598fc35afb202ea9ac0a3c0\` ON \`ledger_entries\``);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` CHANGE \`idempotencyKey\` \`idempotencyKey\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`idempotency_records\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`idempotency_records\` DROP COLUMN \`response\``);
        await queryRunner.query(`ALTER TABLE \`idempotency_records\` ADD \`response\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` CHANGE \`rngAuditLogId\` \`rngAuditLogId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` CHANGE \`executedAt\` \`executedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` CHANGE \`settledAt\` \`settledAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` DROP COLUMN \`settlementSummary\``);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` ADD \`settlementSummary\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` DROP COLUMN \`walletDebit\``);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` ADD \`walletDebit\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` DROP COLUMN \`walletCredit\``);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` ADD \`walletCredit\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`crashPointX100\` \`crashPointX100\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`seed\` \`seed\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`startedAt\` \`startedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`crashedAt\` \`crashedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`elapsedMs\` \`elapsedMs\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` DROP COLUMN \`settlementSummary\``);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` ADD \`settlementSummary\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` CHANGE \`autoCashoutX100\` \`autoCashoutX100\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` CHANGE \`cashedOutAtX100\` \`cashedOutAtX100\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` DROP COLUMN \`walletDebit\``);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` ADD \`walletDebit\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` DROP COLUMN \`walletCredit\``);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` ADD \`walletCredit\` json NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_3347cd4c1c849529f20f48a9c1\` ON \`broadcast_messages\``);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`text\` \`text\` text CHARACTER SET "utf8mb4" COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`imagePath\` \`imagePath\` varchar(300) NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` DROP COLUMN \`buttons\``);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` ADD \`buttons\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` DROP COLUMN \`recurrence\``);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` ADD \`recurrence\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`nextRunAt\` \`nextRunAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`lastRunAt\` \`lastRunAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`lastError\` \`lastError\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` DROP COLUMN \`settlementSummary\``);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` ADD \`settlementSummary\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` CHANGE \`activeGuard\` \`activeGuard\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` CHANGE \`cartelaNumber\` \`cartelaNumber\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` CHANGE \`cardId\` \`cardId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` DROP COLUMN \`walletDebit\``);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` ADD \`walletDebit\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_config\` CHANGE \`prefilledWinPatternId\` \`prefilledWinPatternId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` DROP COLUMN \`mask\``);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` ADD \`mask\` json NULL`);
        await queryRunner.query(`DROP INDEX \`IX_bingo_card_room_assigned\` ON \`bingo_cards\``);
        await queryRunner.query(`ALTER TABLE \`bingo_cards\` CHANGE \`assignedTicketId\` \`assignedTicketId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`bingo_cards\` CHANGE \`assignedUserId\` \`assignedUserId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`refresh_sessions\` CHANGE \`revokedAt\` \`revokedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`refresh_sessions\` CHANGE \`lastUsedAt\` \`lastUsedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` DROP FOREIGN KEY \`FK_63685f0820f59a928efb96686f5\``);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`withdrawalId\` \`withdrawalId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`ledgerEntryId\` \`ledgerEntryId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`amountMinor\` \`amountMinor\` bigint NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_ecc52116ea1cd32c3379352416\` ON \`auth_identities\` (\`operatorId\`, \`provider\`, \`providerUserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_00add8ebb1169bccfc0227e2c3\` ON \`agent_shifts\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_57d6dcdfa66baa83402ca3abac\` ON \`users\` (\`operatorId\`, \`username\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_217a7b342e187cdd5c49c06ea8\` ON \`users\` (\`operatorId\`, \`email\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3315aad10f3a474093ed0809db\` ON \`withdrawals\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d15ac889f39c4793b9eb0554c4\` ON \`withdrawals\` (\`agentId\`, \`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8b5206ce4894004bf8ae882428\` ON \`rng_audit_logs\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_54952f182cfe70ca4c80caffee\` ON \`wager_limits\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bf6dcfed1830bddd9fb012070c\` ON \`telebirr_deposits\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_38e598fc35afb202ea9ac0a3c0\` ON \`ledger_entries\` (\`userId\`, \`sourceType\`, \`idempotencyKey\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a2c65417f2ea9c7a23454e8ffd\` ON \`keno_configs\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_2590cbfc2071c2758a15f7c981\` ON \`keno_configs\` (\`operatorId\`, \`version\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_89592b950a52ad35ca37830b06\` ON \`keno_draws\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d55dbd5ce5fe55339af061624d\` ON \`keno_tickets\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_781747fe9a09eeec1fc6d0d5d1\` ON \`crash_rounds\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e5af947a08c5b1e3139bcac86c\` ON \`crash_bets\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_2234fa349abeeb002602002c74\` ON \`broadcast_messages\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3347cd4c1c849529f20f48a9c1\` ON \`broadcast_messages\` (\`status\`, \`nextRunAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e1b7b02ee1c7da97c642a1f844\` ON \`bingo_rooms\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_bingo_active_game\` ON \`bingo_rooms\` (\`operatorId\`, \`activeGuard\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0da4ea48ffe617b5b8b840b1a6\` ON \`bingo_tickets\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8265314d1e71d46e6ad4cabeaa\` ON \`bingo_patterns\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_5f712872dbbd247d0309202125\` ON \`bingo_cards\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IX_bingo_card_room_assigned\` ON \`bingo_cards\` (\`roomId\`, \`assignedTicketId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4e8666eb1904fb8b9ed22657e0\` ON \`refresh_sessions\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_27a65d6d20c3e3697e5fe4b7b6\` ON \`agent_action_logs\` (\`operatorId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_265ea185d6b4875544777388a1\` ON \`admin_audit_logs\` (\`operatorId\`)`);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` ADD CONSTRAINT \`FK_7739ad242a592b3e80d86a4c42b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` ADD CONSTRAINT \`FK_c9e099b1be330ca21906b5d4b36\` FOREIGN KEY (\`agentId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` ADD CONSTRAINT \`FK_a12d7d24d3d1071edcaffbe7120\` FOREIGN KEY (\`processorId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` ADD CONSTRAINT \`FK_3601e114fb791d969f6694c8db5\` FOREIGN KEY (\`agentId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` ADD CONSTRAINT \`FK_63685f0820f59a928efb96686f5\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` DROP FOREIGN KEY \`FK_63685f0820f59a928efb96686f5\``);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` DROP FOREIGN KEY \`FK_3601e114fb791d969f6694c8db5\``);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` DROP FOREIGN KEY \`FK_a12d7d24d3d1071edcaffbe7120\``);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` DROP FOREIGN KEY \`FK_c9e099b1be330ca21906b5d4b36\``);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` DROP FOREIGN KEY \`FK_7739ad242a592b3e80d86a4c42b\``);
        await queryRunner.query(`DROP INDEX \`IDX_265ea185d6b4875544777388a1\` ON \`admin_audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_27a65d6d20c3e3697e5fe4b7b6\` ON \`agent_action_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_4e8666eb1904fb8b9ed22657e0\` ON \`refresh_sessions\``);
        await queryRunner.query(`DROP INDEX \`IX_bingo_card_room_assigned\` ON \`bingo_cards\``);
        await queryRunner.query(`DROP INDEX \`IDX_5f712872dbbd247d0309202125\` ON \`bingo_cards\``);
        await queryRunner.query(`DROP INDEX \`IDX_8265314d1e71d46e6ad4cabeaa\` ON \`bingo_patterns\``);
        await queryRunner.query(`DROP INDEX \`IDX_0da4ea48ffe617b5b8b840b1a6\` ON \`bingo_tickets\``);
        await queryRunner.query(`DROP INDEX \`UQ_bingo_active_game\` ON \`bingo_rooms\``);
        await queryRunner.query(`DROP INDEX \`IDX_e1b7b02ee1c7da97c642a1f844\` ON \`bingo_rooms\``);
        await queryRunner.query(`DROP INDEX \`IDX_3347cd4c1c849529f20f48a9c1\` ON \`broadcast_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_2234fa349abeeb002602002c74\` ON \`broadcast_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_e5af947a08c5b1e3139bcac86c\` ON \`crash_bets\``);
        await queryRunner.query(`DROP INDEX \`IDX_781747fe9a09eeec1fc6d0d5d1\` ON \`crash_rounds\``);
        await queryRunner.query(`DROP INDEX \`IDX_d55dbd5ce5fe55339af061624d\` ON \`keno_tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_89592b950a52ad35ca37830b06\` ON \`keno_draws\``);
        await queryRunner.query(`DROP INDEX \`IDX_2590cbfc2071c2758a15f7c981\` ON \`keno_configs\``);
        await queryRunner.query(`DROP INDEX \`IDX_a2c65417f2ea9c7a23454e8ffd\` ON \`keno_configs\``);
        await queryRunner.query(`DROP INDEX \`IDX_38e598fc35afb202ea9ac0a3c0\` ON \`ledger_entries\``);
        await queryRunner.query(`DROP INDEX \`IDX_bf6dcfed1830bddd9fb012070c\` ON \`telebirr_deposits\``);
        await queryRunner.query(`DROP INDEX \`IDX_54952f182cfe70ca4c80caffee\` ON \`wager_limits\``);
        await queryRunner.query(`DROP INDEX \`IDX_8b5206ce4894004bf8ae882428\` ON \`rng_audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_d15ac889f39c4793b9eb0554c4\` ON \`withdrawals\``);
        await queryRunner.query(`DROP INDEX \`IDX_3315aad10f3a474093ed0809db\` ON \`withdrawals\``);
        await queryRunner.query(`DROP INDEX \`IDX_217a7b342e187cdd5c49c06ea8\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_57d6dcdfa66baa83402ca3abac\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_00add8ebb1169bccfc0227e2c3\` ON \`agent_shifts\``);
        await queryRunner.query(`DROP INDEX \`IDX_ecc52116ea1cd32c3379352416\` ON \`auth_identities\``);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`amountMinor\` \`amountMinor\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`ledgerEntryId\` \`ledgerEntryId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`withdrawalId\` \`withdrawalId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` ADD CONSTRAINT \`FK_63685f0820f59a928efb96686f5\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refresh_sessions\` CHANGE \`lastUsedAt\` \`lastUsedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`refresh_sessions\` CHANGE \`revokedAt\` \`revokedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_cards\` CHANGE \`assignedUserId\` \`assignedUserId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_cards\` CHANGE \`assignedTicketId\` \`assignedTicketId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IX_bingo_card_room_assigned\` ON \`bingo_cards\` (\`roomId\`, \`assignedTicketId\`)`);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` DROP COLUMN \`mask\``);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` ADD \`mask\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_config\` CHANGE \`prefilledWinPatternId\` \`prefilledWinPatternId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` DROP COLUMN \`walletDebit\``);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` ADD \`walletDebit\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` CHANGE \`cardId\` \`cardId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` CHANGE \`cartelaNumber\` \`cartelaNumber\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` CHANGE \`activeGuard\` \`activeGuard\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` DROP COLUMN \`settlementSummary\``);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` ADD \`settlementSummary\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`createdBy\` \`createdBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`lastError\` \`lastError\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`lastRunAt\` \`lastRunAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`nextRunAt\` \`nextRunAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` DROP COLUMN \`recurrence\``);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` ADD \`recurrence\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` DROP COLUMN \`buttons\``);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` ADD \`buttons\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`imagePath\` \`imagePath\` varchar(300) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` CHANGE \`text\` \`text\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IDX_3347cd4c1c849529f20f48a9c1\` ON \`broadcast_messages\` (\`status\`, \`nextRunAt\`)`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` DROP COLUMN \`walletCredit\``);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` ADD \`walletCredit\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` DROP COLUMN \`walletDebit\``);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` ADD \`walletDebit\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` CHANGE \`cashedOutAtX100\` \`cashedOutAtX100\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` CHANGE \`autoCashoutX100\` \`autoCashoutX100\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` DROP COLUMN \`settlementSummary\``);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` ADD \`settlementSummary\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`elapsedMs\` \`elapsedMs\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`crashedAt\` \`crashedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`startedAt\` \`startedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`seed\` \`seed\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` CHANGE \`crashPointX100\` \`crashPointX100\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` DROP COLUMN \`walletCredit\``);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` ADD \`walletCredit\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` DROP COLUMN \`walletDebit\``);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` ADD \`walletDebit\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` DROP COLUMN \`settlementSummary\``);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` ADD \`settlementSummary\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` CHANGE \`settledAt\` \`settledAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` CHANGE \`executedAt\` \`executedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` CHANGE \`rngAuditLogId\` \`rngAuditLogId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`idempotency_records\` DROP COLUMN \`response\``);
        await queryRunner.query(`ALTER TABLE \`idempotency_records\` ADD \`response\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`idempotency_records\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` CHANGE \`idempotencyKey\` \`idempotencyKey\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ledger_entries\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_38e598fc35afb202ea9ac0a3c0\` ON \`ledger_entries\` (\`userId\`, \`sourceType\`, \`idempotencyKey\`)`);
        await queryRunner.query(`ALTER TABLE \`operators\` DROP COLUMN \`branding\``);
        await queryRunner.query(`ALTER TABLE \`operators\` ADD \`branding\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operators\` CHANGE \`customDomain\` \`customDomain\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operator_configs\` CHANGE \`telegramBotUsername\` \`telegramBotUsername\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operator_configs\` CHANGE \`telegramBotToken\` \`telegramBotToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` DROP COLUMN \`walletCredit\``);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` ADD \`walletCredit\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` DROP COLUMN \`verification\``);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` ADD \`verification\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`transactionStatus\` \`transactionStatus\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`creditedPartyAccount\` \`creditedPartyAccount\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`creditedPartyName\` \`creditedPartyName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`payerPhone\` \`payerPhone\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`payerName\` \`payerName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` CHANGE \`agentId\` \`agentId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` ADD CONSTRAINT \`FK_3601e114fb791d969f6694c8db5\` FOREIGN KEY (\`agentId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rng_audit_logs\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`rng_audit_logs\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`processorId\` \`processorId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`processedAt\` \`processedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`processedBy\` \`processedBy\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`adminNotes\` \`adminNotes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`telebirrReference\` \`telebirrReference\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`netAmountMinor\` \`netAmountMinor\` bigint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`claimedAt\` \`claimedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` CHANGE \`agentId\` \`agentId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IDX_d15ac889f39c4793b9eb0554c4\` ON \`withdrawals\` (\`agentId\`, \`status\`)`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` ADD CONSTRAINT \`FK_a12d7d24d3d1071edcaffbe7120\` FOREIGN KEY (\`processorId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` ADD CONSTRAINT \`FK_c9e099b1be330ca21906b5d4b36\` FOREIGN KEY (\`agentId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`agentPermissions\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`agentPermissions\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workEndMinute\` \`workEndMinute\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workEndHour\` \`workEndHour\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workStartMinute\` \`workStartMinute\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`workStartHour\` \`workStartHour\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`productMetadata\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`productMetadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`responsibleGamingFlags\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`responsibleGamingFlags\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLoginAt\` \`lastLoginAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_217a7b342e187cdd5c49c06ea8\` ON \`users\` (\`operatorId\`, \`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_57d6dcdfa66baa83402ca3abac\` ON \`users\` (\`operatorId\`, \`username\`)`);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` CHANGE \`label\` \`label\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` ADD CONSTRAINT \`FK_7739ad242a592b3e80d86a4c42b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wallets\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` DROP COLUMN \`profileSnapshot\``);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` ADD \`profileSnapshot\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`passwordHash\` \`passwordHash\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`normalizedEmail\` \`normalizedEmail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`providerUsername\` \`providerUsername\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`auth_identities\` CHANGE \`operatorId\` \`operatorId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_ecc52116ea1cd32c3379352416\` ON \`auth_identities\` (\`operatorId\`, \`provider\`, \`providerUserId\`)`);
        await queryRunner.query(`ALTER TABLE \`admin_audit_logs\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`agent_action_logs\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`refresh_sessions\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`bingo_cards\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`bingo_patterns\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`bingo_tickets\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`bingo_rooms\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`broadcast_messages\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`crash_bets\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`crash_rounds\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`keno_tickets\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`keno_draws\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`keno_configs\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`telebirr_deposits\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`wager_limits\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`rng_audit_logs\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`withdrawals\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`ALTER TABLE \`agent_shifts\` DROP COLUMN \`operatorId\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_bingo_active_game\` ON \`bingo_rooms\` (\`activeGuard\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_e623318f79b0e8cdd4d5fa99ec\` ON \`keno_configs\` (\`version\`)`);
    }

}
