import {
    Injectable,
    NotFoundException,
    BadRequestException,
    ForbiddenException,
    ConflictException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, In, Repository } from 'typeorm';
import { WalletService } from '../wallet/wallet.service';
import { AgentShift } from './entities/agent-shift.entity';
import { CreateShiftDto } from './dto/create-shift.dto';
import { UsersService } from '../users/users.service';
import { SystemConfig } from '../admin/entities/system-config.entity';
import { WithdrawalFeeRange } from '../wallet/entities/withdrawal-fee-range.entity';
import { resolveWithdrawalFeeMinor } from '../wallet/withdrawal-fee-range.util';
import { isAgentEffectivelyOnDuty } from '../common/agent-duty.util';
import { buildReferralPayload } from '../common/referral-code.util';
import {
    PayoutProvider,
    WithdrawalProofVerifierService,
} from './withdrawal-proof-verifier.service';
import {
    AgentSettlement,
    AgentSettlementPaymentMethod,
    AgentSettlementStatus,
} from './entities/agent-settlement.entity';

type SettlementBlockReason =
    | 'pending_exists'
    | 'cooldown'
    | 'nothing_to_settle'
    | null;

/** All ledger `sourceType`s that represent referral commission, across every game that pays it. */
export const REFERRAL_COMMISSION_SOURCE_TYPES = [
    'bingo_referral_commission',
    'keno_referral_commission',
    'crash_referral_commission',
    'pool_referral_commission',
    'werk_referral_commission',
];
const REFERRAL_COMMISSION_SOURCE_TYPES_SQL = REFERRAL_COMMISSION_SOURCE_TYPES.map(
    (t) => `'${t}'`,
).join(', ');

@Injectable()
export class AgentsService {
    constructor(
        @InjectRepository(AgentShift)
        private readonly agentShiftRepository: Repository<AgentShift>,
        @InjectRepository(SystemConfig)
        private readonly systemConfigRepository: Repository<SystemConfig>,
        @InjectRepository(WithdrawalFeeRange)
        private readonly withdrawalFeeRangeRepository: Repository<WithdrawalFeeRange>,
        private readonly walletService: WalletService,
        private readonly usersService: UsersService,
        private readonly withdrawalProofVerifier: WithdrawalProofVerifierService,
        private readonly configService: ConfigService,
        private readonly dataSource: DataSource,
        @InjectRepository(AgentSettlement)
        private readonly agentSettlementRepository: Repository<AgentSettlement>,
    ) {}

    /**
     * Earnings the agent has actually EARNED (as opposed to what's been settled/paid
     * out to them  see AgentSettlement). "Game commission" is the referral
     * commission credited via `agent_receipt` ledger entries whose `sourceType`
     * is one of `REFERRAL_COMMISSION_SOURCE_TYPES`  a % of that game's stake
     * (or, for Bingo/Crash, stake × house-edge%) generated by players the agent
     * referred, across every game that pays commission (Bingo, Keno, Crash,
     * Pool, Werk). There is no separate room-owner commission (removed
     * `bingo_room_commission` is no longer written by anything; any pre-existing
     * such entries are historical and excluded from this summary). Withdrawal
     * fees are tracked separately. The
     * `payout_custody` withdrawal credit (reimbursing cash the agent already paid
     * out) is deliberately excluded  it isn't earnings. `deposit_commission` is
     * also excluded  it's a defunct source no longer written anywhere.
     * `period.start`/`period.end` restrict to a window (e.g. today, this month, or
     * a settlement's covered range); omit both for lifetime-to-date.
     */
    async computeAgentEarnings(
        agentId: string,
        period?: { start?: Date; end?: Date },
    ): Promise<{
        referralCommissionMinor: number;
        referralCommissionCount: number;
        gameCommissionMinor: number;
        withdrawalFeesMinor: number;
        totalEarningsMinor: number;
    }> {
        const params: unknown[] = [agentId];
        let dateClause = '';
        if (period?.start) {
            dateClause += ' AND createdAt >= ?';
            params.push(period.start);
        }
        if (period?.end) {
            dateClause += ' AND createdAt < ?';
            params.push(period.end);
        }

        const [row] = await this.systemConfigRepository.query(
            `SELECT
         COALESCE(SUM(CASE WHEN sourceType IN (${REFERRAL_COMMISSION_SOURCE_TYPES_SQL}) THEN amountMinor ELSE 0 END), 0) referralCommission,
         COUNT(CASE WHEN sourceType IN (${REFERRAL_COMMISSION_SOURCE_TYPES_SQL}) THEN 1 END) referralCommissionCount,
         COALESCE(SUM(CASE WHEN sourceType = 'withdrawal' AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.kind')) = 'withdrawal_fee' THEN amountMinor ELSE 0 END), 0) withdrawalFees
       FROM ledger_entries
       WHERE userId = ? AND entryType = 'agent_receipt' AND direction = 'credit'${dateClause}`,
            params,
        );

        const referralCommissionMinor = Number(row?.referralCommission ?? 0);
        const referralCommissionCount = Number(
            row?.referralCommissionCount ?? 0,
        );
        const withdrawalFeesMinor = Number(row?.withdrawalFees ?? 0);
        const gameCommissionMinor = referralCommissionMinor;
        return {
            referralCommissionMinor,
            referralCommissionCount,
            gameCommissionMinor,
            withdrawalFeesMinor,
            totalEarningsMinor: gameCommissionMinor + withdrawalFeesMinor,
        };
    }

    // ── Config (agent-accessible) ────────────────────────────────────

    async getAgentConfig(): Promise<{
        withdrawalFeeRanges: WithdrawalFeeRange[];
    }> {
        const withdrawalFeeRanges =
            await this.withdrawalFeeRangeRepository.find({
                where: { active: true },
                order: { minAmountMinor: 'ASC' },
            });
        return { withdrawalFeeRanges };
    }

    // ── Withdrawals ────────────────────────────────────────────────────

    getAvailableWithdrawals(agentId: string) {
        return this.walletService.getAvailableWithdrawals(agentId);
    }

    getMyWithdrawals(agentId: string) {
        return this.walletService.getAgentWithdrawals(agentId);
    }

    async getTransactionHistory(agentId: string) {
        const [ledger, withdrawals] = await Promise.all([
            this.walletService.getLedgerEntries({
                userId: agentId,
                limit: 100,
            }),
            this.walletService.getAgentWithdrawalHistory(agentId),
        ]);

        return { ledger, withdrawals };
    }

    /**
     * Unified agent gate: an agent may only act while **effectively on duty**  i.e.
     * inside their working window (Ethiopia time) or manually pinned on  and only
     * for actions their permissions allow. All time math is Ethiopia-based, so it no
     * longer depends on the server clock.
     */
    verifyAgentWorkingHoursAndPermission(
        agent: any,
        permission: 'deposit' | 'withdraw',
    ) {
        // 1. Must be on duty (scheduled window or admin override).
        if (!isAgentEffectivelyOnDuty(agent)) {
            throw new BadRequestException(
                'You are off duty right now (outside your working hours).',
            );
        }

        // 2. Must have permission for this action.
        if (
            agent.agentPermissions &&
            agent.agentPermissions[permission] === false
        ) {
            throw new BadRequestException(
                `Agent does not have ${permission} permission`,
            );
        }
    }

    async claimWithdrawal(withdrawalId: string, agentId: string) {
        const agent = await this.usersService.findById(agentId);
        this.verifyAgentWorkingHoursAndPermission(agent, 'withdraw');
        return this.walletService.claimWithdrawal(withdrawalId, agentId);
    }

    async releaseWithdrawal(withdrawalId: string, agentId: string) {
        const agent = await this.usersService.findById(agentId);
        this.verifyAgentWorkingHoursAndPermission(agent, 'withdraw');
        return this.walletService.releaseWithdrawal(withdrawalId, agentId);
    }

    async completeWithdrawal(
        withdrawalId: string,
        agentId: string,
        provider: PayoutProvider,
        proof: string,
        receiptFileUrl: string,
        transferCompletedAt: Date,
    ) {
        const agent = await this.usersService.findById(agentId);
        this.verifyAgentWorkingHoursAndPermission(agent, 'withdraw');
        const config = await this.systemConfigRepository.findOneBy({
            key: 'global',
        });
        const creditMinorPerBirr = config?.telebirrCreditMinorPerBirr ?? 1;

        // The withdrawal must be claimed by THIS agent, and we need its destination
        // (the player's phone) and amount to check the payout proof against.
        const withdrawal =
            await this.walletService.getClaimedWithdrawalForAgent(
                withdrawalId,
                agentId,
            );

        // Resolve the flat fee for this amount from the admin-configured ranges. The
        // agent keeps 100% of it  no platform split.
        const activeRanges = await this.withdrawalFeeRangeRepository.find({
            where: { active: true },
        });
        const feeMinor = resolveWithdrawalFeeMinor(
            withdrawal.amountMinor,
            activeRanges,
        );

        // The player receives the net amount (gross − fee); that is exactly what the
        // agent must have paid out.
        const expectedAmountMinor = withdrawal.amountMinor - feeMinor;

        // Verify the agent actually paid the player before releasing frozen coins.
        const verified = await this.withdrawalProofVerifier.verifyPayout({
            provider,
            proof,
            destinationAccount: withdrawal.destinationAccount,
            expectedAmountMinor,
            creditMinorPerBirr,
        });

        // Records the proof only  money doesn't move until an admin verifies it
        // (see WalletService.verifyAgentWithdrawal).
        return this.walletService.recordAgentWithdrawalProof({
            withdrawalId,
            agentId,
            telebirrReference: verified.reference,
            paymentProvider: verified.provider,
            payoutVerification: verified.verification,
            receiptFileUrl,
            transferCompletedAt,
            feeMinor,
        });
    }

    // ── Shifts ─────────────────────────────────────────────────────────

    async createShift(dto: CreateShiftDto): Promise<any> {
        const shift = this.agentShiftRepository.create({
            agentId: dto.agentId,
            startHour: dto.startHour,
            startMinute: dto.startMinute,
            endHour: dto.endHour,
            endMinute: dto.endMinute,
            daysOfWeek: dto.daysOfWeek ?? [],
            label: dto.label,
            isActive: dto.isActive ?? true,
        });
        await this.agentShiftRepository.save(shift);

        const saved = await this.agentShiftRepository.findOne({
            where: { id: shift.id },
            relations: ['user'],
        });
        return this.toShiftResponse(saved!);
    }

    async listShifts(): Promise<any[]> {
        const shifts = await this.agentShiftRepository.find({
            relations: ['user'],
            order: { startHour: 'ASC', startMinute: 'ASC' },
        });
        return shifts.map((s) => this.toShiftResponse(s));
    }

    async updateShift(
        shiftId: string,
        dto: Partial<CreateShiftDto>,
    ): Promise<any> {
        const shift = await this.agentShiftRepository.findOneBy({
            id: shiftId,
        });
        if (!shift) throw new NotFoundException('Shift not found');

        if (dto.agentId !== undefined) shift.agentId = dto.agentId;
        if (dto.startHour !== undefined) shift.startHour = dto.startHour;
        if (dto.startMinute !== undefined) shift.startMinute = dto.startMinute;
        if (dto.endHour !== undefined) shift.endHour = dto.endHour;
        if (dto.endMinute !== undefined) shift.endMinute = dto.endMinute;
        if (dto.daysOfWeek !== undefined) shift.daysOfWeek = dto.daysOfWeek;
        if (dto.label !== undefined) shift.label = dto.label;
        if (dto.isActive !== undefined) shift.isActive = dto.isActive;

        await this.agentShiftRepository.save(shift);

        const saved = await this.agentShiftRepository.findOne({
            where: { id: shift.id },
            relations: ['user'],
        });
        return this.toShiftResponse(saved!);
    }

    async deleteShift(shiftId: string): Promise<void> {
        await this.agentShiftRepository.delete({ id: shiftId });
    }

    /**
     * Returns the agentId of the shift that covers the current moment,
     * or null if no active shift matches.
     * Overnight shifts (endTime < startTime) are handled correctly.
     */
    async getActiveShiftAgentId(): Promise<string | null> {
        const now = new Date();
        const dayOfWeek = now.getDay();
        const currentMinutes = now.getHours() * 60 + now.getMinutes();

        const shifts = await this.agentShiftRepository.findBy({
            isActive: true,
        });

        for (const shift of shifts) {
            const dayMatch =
                shift.daysOfWeek.length === 0 ||
                shift.daysOfWeek.includes(dayOfWeek);
            if (!dayMatch) continue;

            const startMinutes = shift.startHour * 60 + shift.startMinute;
            const endMinutes = shift.endHour * 60 + shift.endMinute;

            const isOvernightShift = endMinutes <= startMinutes;
            const inWindow = isOvernightShift
                ? currentMinutes >= startMinutes || currentMinutes < endMinutes
                : currentMinutes >= startMinutes && currentMinutes < endMinutes;

            if (inWindow) {
                return shift.agentId;
            }
        }

        return null;
    }

    async getActiveShift(): Promise<any | null> {
        const now = new Date();
        const dayOfWeek = now.getDay();
        const currentMinutes = now.getHours() * 60 + now.getMinutes();

        const shifts = await this.agentShiftRepository.find({
            where: { isActive: true },
            relations: ['user'],
        });

        for (const shift of shifts) {
            const dayMatch =
                shift.daysOfWeek.length === 0 ||
                shift.daysOfWeek.includes(dayOfWeek);
            if (!dayMatch) continue;

            const startMinutes = shift.startHour * 60 + shift.startMinute;
            const endMinutes = shift.endHour * 60 + shift.endMinute;

            const isOvernightShift = endMinutes <= startMinutes;
            const inWindow = isOvernightShift
                ? currentMinutes >= startMinutes || currentMinutes < endMinutes
                : currentMinutes >= startMinutes && currentMinutes < endMinutes;

            if (inWindow) return this.toShiftResponse(shift);
        }

        return null;
    }

    /**
     * Player-facing: the Telebirr deposit details of the agent currently on
     * shift. Returns only the public info a depositing user needs
     * (full name + Telebirr phone number). Null when nobody is on shift.
     */
    async getActiveAgentDepositInfo(): Promise<{
        displayName: string;
        phoneNumber: string | null;
    } | null> {
        // The deposit destination is simply whichever agent the admin has on duty
        // (single primary). No timezone / schedule math  it's an explicit switch.
        const agent = await this.usersService.findOnDutyAgent();
        if (!agent) return null;

        // An on-duty agent still needs the deposit permission to receive deposits.
        if (agent.agentPermissions && agent.agentPermissions.deposit === false)
            return null;

        // An agent with no admin-allocated deposit float left isn't shown as a
        // deposit destination  treat them the same as not currently available.
        // Deliberately NOT the raw wallet balance: that also includes referral
        // commission and withdrawal-payout reimbursement credits, which would
        // let an unfunded agent pass this check just by having an active
        // referred player (see WalletService.getAgentFloatRemaining).
        const floatRemaining = await this.walletService.getAgentFloatRemaining(
            [agent.id],
        );
        if ((floatRemaining.get(agent.id) ?? 0) <= 0) return null;

        return {
            displayName: agent.displayName,
            phoneNumber: agent.phoneNumber ?? null,
        };
    }

    /**
     * Player-facing: ALL agents currently on duty that can receive deposits  so the
     * player can CHOOSE who to send their Telebirr transfer to when more than one is
     * available. Returns public info only (id + name + Telebirr phone). Empty when
     * nobody is on duty. Deposit attribution is still driven by the receipt itself
     * (the verifier matches the recipient name/phone), so this is purely a chooser.
     * An agent with no admin-allocated deposit float left is excluded  same
     * reasoning as getActiveAgentDepositInfo above.
     */
    async getActiveAgentsDepositInfo(): Promise<
        Array<{
            id: string;
            displayName: string;
            phoneNumber: string | null;
            /** M-Pesa deposit destination  falls back to phoneNumber when the
             * agent hasn't set a separate one, so callers never need their own fallback. */
            mpesaPhoneNumber: string | null;
        }>
    > {
        const agents = await this.usersService.findOnDutyAgents();
        const eligible = agents.filter(
            (a) =>
                !(a.agentPermissions && a.agentPermissions.deposit === false),
        );
        if (eligible.length === 0) return [];

        const floatRemaining = await this.walletService.getAgentFloatRemaining(
            eligible.map((a) => a.id),
        );
        return eligible
            .filter((a) => (floatRemaining.get(a.id) ?? 0) > 0)
            .map((a) => ({
                id: a.id,
                displayName: a.displayName,
                phoneNumber: a.phoneNumber ?? null,
                mpesaPhoneNumber: a.mpesaPhoneNumber ?? a.phoneNumber ?? null,
            }));
    }

    /**
     * The agent's shareable referral link. The code is generated on first access for
     * agents created before referral codes existed, so this is safe to call for any
     * agent. `link` is null when TELEGRAM_BOT_USERNAME is not configured  the code
     * itself is still returned so the agent can pass it on manually.
     */
    async getReferral(agentId: string): Promise<{
        code: string;
        link: string | null;
        referredPlayers: number;
    }> {
        const [code, referredPlayers] = await Promise.all([
            this.usersService.ensureAgentReferralCode(agentId),
            this.usersService.countReferredPlayers(agentId),
        ]);

        const botUsername = this.configService
            .get<string>('TELEGRAM_BOT_USERNAME', '')
            .trim()
            .replace(/^@/, '');

        return {
            code,
            link: botUsername
                ? `https://t.me/${botUsername}?start=${buildReferralPayload(code)}`
                : null,
            referredPlayers,
        };
    }

    /**
     * The requesting agent's own Bingo performance (Approach B): customers brought,
     * real-player activity in their OWNED ROOMS (bots excluded), GGR, and their
     * (referral-based) commission earned overall. Note `commissionEarnedMinor` is
     * scoped to REFERRED players, a different population than the room-activity
     * fields above (owned-room traffic)  there is no room-owner commission.
     */
    async getPerformance(agentId: string): Promise<{
        customersBrought: number;
        tickets: number;
        players: number;
        stakedMinor: number;
        payoutMinor: number;
        ggrMinor: number;
        commissionEarnedMinor: number;
        withdrawalFeesEarnedMinor: number;
        depositCount: number;
        depositVolumeMinor: number;
        depositCommissionEarnedMinor: number;
    }> {
        const q = (sql: string, params: unknown[]) =>
            this.systemConfigRepository.query(sql, params);
        const [play] = await q(
            `SELECT COUNT(*) tickets, COUNT(DISTINCT t.userId) players,
              COALESCE(SUM(t.stakeMinor),0) staked, COALESCE(SUM(t.payoutMinor),0) payout
         FROM bingo_tickets t JOIN users pu ON pu.id = t.userId
        WHERE t.agentId = ? AND t.status <> 'cancelled'
          AND JSON_EXTRACT(pu.productMetadata, '$.botPolicy') IS NULL`,
            [agentId],
        );
        const earnings = await this.computeAgentEarnings(agentId);
        const [cust] = await q(
            `SELECT COUNT(*) customers FROM users WHERE referredByAgentId = ?`,
            [agentId],
        );

        // Phase 4  deposit activity the agent processed (volume/count from the
        // deposit-receipt action log), and the commission it earned them.
        const [dep] = await q(
            `SELECT COUNT(*) deposits, COALESCE(SUM(amountMinor),0) volume FROM agent_action_logs
        WHERE agentId = ? AND actionType IN ('telebirr_deposit_receipt','mpesa_deposit_receipt')`,
            [agentId],
        );
        const [depComm] = await q(
            `SELECT COALESCE(SUM(amountMinor),0) commission FROM ledger_entries
        WHERE userId = ? AND entryType = 'agent_receipt' AND sourceType = 'deposit_commission'`,
            [agentId],
        );

        const stakedMinor = Number(play?.staked ?? 0);
        const payoutMinor = Number(play?.payout ?? 0);
        return {
            customersBrought: Number(cust?.customers ?? 0),
            tickets: Number(play?.tickets ?? 0),
            players: Number(play?.players ?? 0),
            stakedMinor,
            payoutMinor,
            ggrMinor: stakedMinor - payoutMinor,
            commissionEarnedMinor: earnings.gameCommissionMinor,
            withdrawalFeesEarnedMinor: earnings.withdrawalFeesMinor,
            depositCount: Number(dep?.deposits ?? 0),
            depositVolumeMinor: Number(dep?.volume ?? 0),
            depositCommissionEarnedMinor: Number(depComm?.commission ?? 0),
        };
    }

    /** Agent Dashboard summary  referred/active players, lifetime earnings by
     * source, settlement standing, and withdrawal request counts. */
    async getDashboardSummary(agentId: string): Promise<{
        totalReferredPlayers: number;
        activePlayers: number;
        gameCommission: { totalMinor: number; count: number };
        withdrawalFeesEarnedMinor: number;
        totalEarningsMinor: number;
        totalSettledMinor: number;
        remainingMinor: number;
        canRequestSettlement: boolean;
        settlementBlockReason: SettlementBlockReason;
        settlementCooldownEndsAt: Date | null;
        pendingWithdrawalRequests: number;
        completedWithdrawalRequests: number;
    }> {
        const activeSince = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

        const [
            totalReferredPlayers,
            activePlayers,
            lifetime,
            eligibility,
            pendingWithdrawalRequests,
            completedWithdrawalRequests,
        ] = await Promise.all([
            this.usersService.countReferredPlayers(agentId),
            this.usersService.countActiveReferredPlayers(agentId, activeSince),
            this.computeAgentEarnings(agentId),
            this.getSettlementEligibility(agentId),
            this.walletService.countPendingAgentWithdrawals(agentId),
            this.walletService.countCompletedAgentWithdrawals(agentId),
        ]);

        return {
            totalReferredPlayers,
            activePlayers,
            gameCommission: {
                totalMinor: lifetime.gameCommissionMinor,
                count: lifetime.referralCommissionCount,
            },
            withdrawalFeesEarnedMinor: lifetime.withdrawalFeesMinor,
            totalEarningsMinor: lifetime.totalEarningsMinor,
            totalSettledMinor: eligibility.totalSettledMinor,
            remainingMinor: eligibility.remainingMinor,
            canRequestSettlement: eligibility.canRequest,
            settlementBlockReason: eligibility.blockReason,
            settlementCooldownEndsAt: eligibility.cooldownEndsAt,
            pendingWithdrawalRequests,
            completedWithdrawalRequests,
        };
    }

    // ── Settlements ──────────────────────────────────────────────────
    // Real-world payouts to an agent, tracked separately from what they've
    // earned (computeAgentEarnings). "Simple" workflow per design: one create
    // endpoint that snapshots the period's earnings, one update endpoint that
    // sets status/payment fields freely  the only enforced rule is that an
    // FT number + receipt must be present before a settlement can be 'paid'.

    /**
     * How much of an agent's lifetime earnings is still unclaimed by any
     * settlement, and whether they're currently allowed to request one.
     * "Claimed" includes 'pending' and 'approved' settlements (not just 'paid')
     * so the displayed remaining/request amount never double-counts money
     * already tied up in an open request  see PROGRESS discussion on
     * agent-initiated settlements.
     */
    private async getSettlementEligibility(agentId: string): Promise<{
        remainingMinor: number;
        claimedMinor: number;
        totalSettledMinor: number;
        canRequest: boolean;
        blockReason: SettlementBlockReason;
        cooldownEndsAt: Date | null;
    }> {
        const [
            lifetime,
            claimedRow,
            settledRow,
            unresolved,
            lastRequested,
            cfg,
        ] = await Promise.all([
            this.computeAgentEarnings(agentId),
            this.agentSettlementRepository
                .createQueryBuilder('s')
                .select('COALESCE(SUM(s.amountPaidMinor), 0)', 'sum')
                .where('s.agentId = :agentId AND s.status IN (:...statuses)', {
                    agentId,
                    statuses: ['paid', 'pending', 'approved'],
                })
                .getRawOne<{ sum: string }>(),
            this.agentSettlementRepository
                .createQueryBuilder('s')
                .select('COALESCE(SUM(s.amountPaidMinor), 0)', 'sum')
                .where('s.agentId = :agentId AND s.status = :status', {
                    agentId,
                    status: 'paid',
                })
                .getRawOne<{ sum: string }>(),
            this.agentSettlementRepository.findOne({
                where: { agentId, status: In(['pending', 'approved']) },
                order: { createdAt: 'DESC' },
            }),
            this.agentSettlementRepository.findOne({
                where: { agentId, requestedByAgent: true },
                order: { createdAt: 'DESC' },
            }),
            this.systemConfigRepository.findOneBy({ key: 'global' }),
        ]);

        const claimedMinor = Number(claimedRow?.sum ?? 0);
        const totalSettledMinor = Number(settledRow?.sum ?? 0);
        const remainingMinor = Math.max(
            0,
            lifetime.totalEarningsMinor - claimedMinor,
        );

        const cooldownHours = cfg?.agentSettlementCooldownHours ?? 0;
        let cooldownEndsAt: Date | null = null;
        if (cooldownHours > 0 && lastRequested) {
            const endsAt = new Date(
                lastRequested.createdAt.getTime() +
                    cooldownHours * 60 * 60 * 1000,
            );
            if (endsAt > new Date()) cooldownEndsAt = endsAt;
        }

        let blockReason: SettlementBlockReason = null;
        if (unresolved) blockReason = 'pending_exists';
        else if (cooldownEndsAt) blockReason = 'cooldown';
        else if (remainingMinor <= 0) blockReason = 'nothing_to_settle';

        return {
            remainingMinor,
            claimedMinor,
            totalSettledMinor,
            canRequest: blockReason === null,
            blockReason,
            cooldownEndsAt,
        };
    }

    /**
     * Agent self-service settlement request  covers the agent's own earnings
     * from the end of their last paid/pending/approved settlement (or their
     * account creation, if they've never had one) through now. Lands as an
     * ordinary 'pending' row in the same admin review queue as an admin-created
     * settlement (see createSettlement below); `requestedByAgent: true` is the
     * only distinguishing mark, used for the cooldown in getSettlementEligibility.
     */
    async requestSettlement(agentId: string): Promise<AgentSettlement> {
        const eligibility = await this.getSettlementEligibility(agentId);
        if (eligibility.blockReason === 'pending_exists') {
            throw new ConflictException(
                'You already have a settlement request awaiting review.',
            );
        }
        if (eligibility.blockReason === 'cooldown') {
            throw new ConflictException(
                `You can request again at ${eligibility.cooldownEndsAt!.toISOString()}.`,
            );
        }
        if (eligibility.blockReason === 'nothing_to_settle') {
            throw new BadRequestException('No new earnings to settle yet.');
        }

        const periodEnd = new Date();
        const lastResolved = await this.agentSettlementRepository.findOne({
            where: { agentId, status: In(['paid', 'pending', 'approved']) },
            order: { periodEnd: 'DESC' },
        });
        const periodStart = lastResolved
            ? lastResolved.periodEnd
            : (await this.usersService.findById(agentId)).createdAt;

        const period = await this.computeAgentEarnings(agentId, {
            start: periodStart,
            end: periodEnd,
        });
        const lifetimeToPeriodEnd = await this.computeAgentEarnings(agentId, {
            end: periodEnd,
        });
        const amountPaidMinor = period.totalEarningsMinor;
        const outstandingBalanceMinor =
            lifetimeToPeriodEnd.totalEarningsMinor -
            (eligibility.claimedMinor + amountPaidMinor);

        return this.dataSource.transaction(async (manager) => {
            const repo = manager.getRepository(AgentSettlement);
            const settlement = repo.create({
                agentId,
                periodStart,
                periodEnd,
                gameCommissionMinor: period.gameCommissionMinor,
                withdrawalFeesMinor: period.withdrawalFeesMinor,
                totalEarnedMinor: period.totalEarningsMinor,
                amountPaidMinor,
                outstandingBalanceMinor,
                status: 'pending',
                requestedByAgent: true,
                notes: null,
            });
            const saved = await repo.save(settlement);

            await this.walletService.recordAgentAction(
                {
                    agentId,
                    actionType: 'settlement_requested',
                    amountMinor: saved.amountPaidMinor,
                    metadata: {
                        settlementId: saved.id,
                        periodStart,
                        periodEnd,
                        status: saved.status,
                    },
                },
                manager,
            );

            return saved;
        });
    }

    async createSettlement(
        agentId: string,
        periodStart: Date,
        periodEnd: Date,
        notes: string | undefined,
    ): Promise<AgentSettlement> {
        const period = await this.computeAgentEarnings(agentId, {
            start: periodStart,
            end: periodEnd,
        });
        const lifetimeToPeriodEnd = await this.computeAgentEarnings(agentId, {
            end: periodEnd,
        });

        const priorPaidRow = await this.agentSettlementRepository
            .createQueryBuilder('s')
            .select('COALESCE(SUM(s.amountPaidMinor), 0)', 'sum')
            .where('s.agentId = :agentId AND s.status = :status', {
                agentId,
                status: 'paid',
            })
            .getRawOne<{ sum: string }>();
        const priorPaidMinor = Number(priorPaidRow?.sum ?? 0);

        // Defaults to the full period earnings; admin can PATCH amountPaidMinor down
        // (partial payment) before marking it paid.
        const amountPaidMinor = period.totalEarningsMinor;
        const outstandingBalanceMinor =
            lifetimeToPeriodEnd.totalEarningsMinor -
            (priorPaidMinor + amountPaidMinor);

        return this.dataSource.transaction(async (manager) => {
            const repo = manager.getRepository(AgentSettlement);
            const settlement = repo.create({
                agentId,
                periodStart,
                periodEnd,
                gameCommissionMinor: period.gameCommissionMinor,
                withdrawalFeesMinor: period.withdrawalFeesMinor,
                totalEarnedMinor: period.totalEarningsMinor,
                amountPaidMinor,
                outstandingBalanceMinor,
                status: 'pending',
                notes: notes ?? null,
            });
            const saved = await repo.save(settlement);

            await this.walletService.recordAgentAction(
                {
                    agentId,
                    actionType: 'settlement_recorded',
                    amountMinor: saved.amountPaidMinor,
                    metadata: {
                        settlementId: saved.id,
                        periodStart,
                        periodEnd,
                        status: saved.status,
                    },
                },
                manager,
            );

            return saved;
        });
    }

    async updateSettlement(
        id: string,
        update: {
            status?: AgentSettlementStatus;
            paymentMethod?: AgentSettlementPaymentMethod | null;
            ftNumber?: string | null;
            receiptFileUrl?: string | null;
            paidAt?: Date | null;
            amountPaidMinor?: number;
            notes?: string | null;
        },
        adminUserId: string,
    ): Promise<AgentSettlement> {
        return this.dataSource.transaction(async (manager) => {
            const repo = manager.getRepository(AgentSettlement);
            const settlement = await repo.findOneBy({ id });
            if (!settlement)
                throw new NotFoundException('Settlement not found');

            const nextStatus = update.status ?? settlement.status;
            const nextFtNumber =
                update.ftNumber !== undefined
                    ? update.ftNumber
                    : settlement.ftNumber;
            const nextReceiptFileUrl =
                update.receiptFileUrl !== undefined
                    ? update.receiptFileUrl
                    : settlement.receiptFileUrl;
            const nextPaymentMethod =
                update.paymentMethod !== undefined
                    ? update.paymentMethod
                    : settlement.paymentMethod;
            // Cash and in-person bank-branch payouts have no verifiable transfer
            // reference, so proof is deliberately not required for them (business
            // decision  those are trusted on the admin's word). Every other method,
            // including leaving it unset, still requires an FT number + receipt.
            const proofExemptMethods: Array<
                AgentSettlementPaymentMethod | null | undefined
            > = ['cash', 'bank_branch'];
            const requiresProof =
                !proofExemptMethods.includes(nextPaymentMethod);
            if (
                nextStatus === 'paid' &&
                requiresProof &&
                (!nextFtNumber || !nextReceiptFileUrl)
            ) {
                throw new BadRequestException(
                    'An FT number and receipt are required to mark a settlement as paid via this payment method',
                );
            }
            if (nextStatus === 'paid' && !requiresProof) {
                // No FT number or receipt exists for cash/branch payouts  a note is the
                // only record that would ever exist of this payment, so it's mandatory.
                const nextNotes =
                    update.notes !== undefined
                        ? update.notes
                        : settlement.notes;
                if (!nextNotes || !nextNotes.trim()) {
                    throw new BadRequestException(
                        'A note describing the payment is required to mark a settlement as paid via cash or bank branch',
                    );
                }
            }

            if (update.status !== undefined) settlement.status = update.status;
            if (update.paymentMethod !== undefined)
                settlement.paymentMethod = update.paymentMethod;
            if (update.ftNumber !== undefined)
                settlement.ftNumber = update.ftNumber;
            if (update.receiptFileUrl !== undefined)
                settlement.receiptFileUrl = update.receiptFileUrl;
            if (update.paidAt !== undefined) settlement.paidAt = update.paidAt;
            if (update.amountPaidMinor !== undefined)
                settlement.amountPaidMinor = update.amountPaidMinor;
            if (update.notes !== undefined) settlement.notes = update.notes;

            if (nextStatus === 'paid') {
                settlement.paidByAdminId = adminUserId;
                if (!settlement.paidAt) settlement.paidAt = new Date();
            }

            const saved = await repo.save(settlement);

            await this.walletService.recordAgentAction(
                {
                    agentId: settlement.agentId,
                    actionType: 'settlement_updated',
                    amountMinor: settlement.amountPaidMinor,
                    metadata: {
                        settlementId: settlement.id,
                        status: settlement.status,
                    },
                },
                manager,
            );

            return saved;
        });
    }

    async listSettlements(
        agentId: string | undefined,
        page: number,
        limit: number,
    ): Promise<{
        data: AgentSettlement[];
        total: number;
        page: number;
        limit: number;
    }> {
        const [data, total] = await this.agentSettlementRepository.findAndCount(
            {
                where: agentId ? { agentId } : {},
                order: { createdAt: 'DESC' },
                skip: (page - 1) * limit,
                take: limit,
            },
        );
        return { data, total, page, limit };
    }

    // ── Area reporting (players directly assigned to this agent) ───────
    //
    // Distinct from getPerformance above: this shows ALL players GPS-matched or
    // manually assigned to this agent (see UsersService.setAssignedAgent), not
    // just players this agent personally processed a deposit for. Each player
    // is additionally flagged `isMyReferral` when referredByAgentId matches
    // this agent  the "mix of both" the requester asked for: full area
    // visibility, with personal referrals called out.

    async listAreaPlayers(
        agentId: string,
        opts: { search?: string; page?: number; limit?: number } = {},
    ): Promise<{
        data: Array<{
            id: string;
            displayName: string;
            phoneNumber: string | null;
            walletBalanceMinor: number;
            status: string;
            isMyReferral: boolean;
            createdAt: Date;
        }>;
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }> {
        const result = await this.usersService.listPlayersByAssignedAgentId(
            agentId,
            opts,
        );

        return {
            ...result,
            data: result.data.map((u) => ({
                id: u.id,
                displayName: u.displayName,
                phoneNumber: u.phoneNumber ?? null,
                walletBalanceMinor:
                    u.wallets?.find((w) => w.currencyCode === 'CREDIT')
                        ?.availableMinor ?? 0,
                status: u.status,
                isMyReferral: u.referredByAgentId === agentId,
                createdAt: u.createdAt,
            })),
        };
    }

    /**
     * Per-player drill-down: deposits, withdrawals, games played/won. Enforces
     * the authorization boundary  the target player MUST be assigned to this
     * agent, otherwise an agent could view any player by guessing a userId.
     */
    async getAreaPlayerActivity(agentId: string, playerUserId: string) {
        const player = await this.usersService.findById(playerUserId);

        if (player.assignedAgentId !== agentId) {
            throw new ForbiddenException(
                'This player is not in your assigned area',
            );
        }

        const q = (sql: string, params: unknown[]) =>
            this.systemConfigRepository.query(sql, params);

        const [
            telebirrDeposits,
            mpesaDeposits,
            withdrawals,
            [bingo],
            [keno],
            [crash],
        ] = await Promise.all([
            q(
                `SELECT id, receiptNo, amountMinor, status, createdAt FROM telebirr_deposits
          WHERE userId = ? ORDER BY createdAt DESC LIMIT 50`,
                [playerUserId],
            ),
            q(
                `SELECT id, confirmationCode, amountMinor, status, createdAt FROM mpesa_deposits
          WHERE userId = ? ORDER BY createdAt DESC LIMIT 50`,
                [playerUserId],
            ),
            q(
                `SELECT id, amountMinor, status, destinationAccount, createdAt, processedAt FROM withdrawals
          WHERE userId = ? ORDER BY createdAt DESC LIMIT 50`,
                [playerUserId],
            ),
            q(
                `SELECT COUNT(*) played, COALESCE(SUM(status='won'),0) won,
                COALESCE(SUM(stakeMinor),0) staked, COALESCE(SUM(payoutMinor),0) payout
           FROM bingo_tickets WHERE userId = ? AND status <> 'cancelled'`,
                [playerUserId],
            ),
            q(
                `SELECT COUNT(*) played, COALESCE(SUM(status='won'),0) won,
                COALESCE(SUM(stakeMinor),0) staked, COALESCE(SUM(payoutMinor),0) payout
           FROM keno_tickets WHERE userId = ? AND status <> 'cancelled'`,
                [playerUserId],
            ),
            q(
                `SELECT COUNT(*) played, COALESCE(SUM(status='won'),0) won,
                COALESCE(SUM(stakeMinor),0) staked, COALESCE(SUM(payoutMinor),0) payout
           FROM crash_bets WHERE userId = ? AND status <> 'active'`,
                [playerUserId],
            ),
        ]);

        const toGameSummary = (
            row:
                | {
                      played?: unknown;
                      won?: unknown;
                      staked?: unknown;
                      payout?: unknown;
                  }
                | undefined,
        ) => ({
            played: Number(row?.played ?? 0),
            won: Number(row?.won ?? 0),
            stakedMinor: Number(row?.staked ?? 0),
            payoutMinor: Number(row?.payout ?? 0),
        });

        return {
            player: {
                id: player.id,
                displayName: player.displayName,
                phoneNumber: player.phoneNumber ?? null,
                isMyReferral: player.referredByAgentId === agentId,
            },
            deposits: {
                telebirr: telebirrDeposits,
                mpesa: mpesaDeposits,
            },
            withdrawals,
            games: {
                bingo: toGameSummary(bingo),
                keno: toGameSummary(keno),
                crash: toGameSummary(crash),
            },
        };
    }

    private toShiftResponse(shift: AgentShift) {
        return {
            id: shift.id,
            agentId: shift.user
                ? {
                      id: shift.user.id,
                      displayName: shift.user.displayName,
                      email: shift.user.email,
                  }
                : shift.agentId,
            startHour: shift.startHour,
            startMinute: shift.startMinute,
            endHour: shift.endHour,
            endMinute: shift.endMinute,
            daysOfWeek: shift.daysOfWeek,
            label: shift.label,
            isActive: shift.isActive,
            createdAt: shift.createdAt,
            updatedAt: shift.updatedAt,
        };
    }
}
